force-app/main/default/objects/Collaborate_Support_Team__mdt/Collaborate_Support_Team__mdt.object-meta.xml
<CustomObject>
    <label>Collaborate Support Team</label>
    <pluralLabel>Collaborate Support Teams</pluralLabel>
</CustomObject>

force-app/main/default/objects/Collaborate_Support_Team__mdt/fields/buttonId__c.field-meta.xml
<CustomField>
    <fullName>buttonId__c</fullName>
    <label>buttonId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborate_Support_Team__mdt/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <label>Queue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER HOURS ENGLISH</fullName>
                <default>true</default>
                <label>AFTER HOURS ENGLISH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collaborate_Support_Team__mdt/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POLICY QUESTION</fullName>
                <default>true</default>
                <label>POLICY QUESTION</label>
            </value>
            <value>
                <fullName>Tag Missing/Order Missing</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collaborate_Support_Team__mdt/fields/Support_Team__c.field-meta.xml
<CustomField>
    <fullName>Support_Team__c</fullName>
    <label>Support Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CENTRALIZED TECH EXPERT</fullName>
                <default>true</default>
                <label>CENTRALIZED TECH EXPERT</label>
            </value>
            <value>
                <fullName>CONSUMER EXCHANGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collaborate_Support_Team__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
                <default>true</default>
                <label>Case</label>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CollaborateInternalCase.cls
/* --------------------------------------------------------------------------------------------------------------------
Name:         CollaborateInternalCase 
Description:  this Controller is used by CollaborationCase.cmp for Story 5820178 & 5820681
Date          Version  Author             Summary of Changes 
-----------  -------  -----------------  -------------------------------------------------------------------------------
12/30/2018     1.0     Brundha Rajkumar     Initial Release

------------------------------------------------------------------------------------------------------------------------ */  


public class CollaborateInternalCase {
    
    
    /* ----------------------------------------------------------------------------------------------------------------------
Name:         createCase
Description:  this functions creates the  Case
-------------------------------------------------------------------------------------------------------------------------*/
    @AuraEnabled
    public static id createCase(string supportTeam,string queueId,string reason,string description,string caseTitle,boolean customerWaiting,Id parentCase,Id accId,Id contactId,Id assetId){
        try{
            case childcase=new case();      
            //childcase.support_team__c=supportTeam;
            //childcase.case_queue__c=queueId;
            //childcase.Internal_Case_Create_Reason__c =reason;
            childcase.Description=description;
            childcase.Subject=caseTitle;
            childcase.status='Open';
            //childcase.Customer_Waiting__c=Boolean.valueOf(customerWaiting);
            //childcase.recordtypeId=system.label.Internal_case;
            childcase.parentId=parentcase;
            childcase.Origin='Internal';
            childcase.AssetId=assetId;
            childcase.AccountId=accId;
            childcase.ContactId=contactId;
            
            insert childcase;        
            return childcase.id;
        }
        catch(exception e){
            //ExceptionHandler.logHandledExceptions(e,'CollaborateInternalCase','createCase','CaseManagement'); 
        }
        return null;
    }
    
    /* ----------------------------------------------------------------------------------------------------------------------
Name:         getOptions
Description:  this function get the records from Custom Metadata type Collaborate_Support_Team__mdt based on the Support Team value
-------------------------------------------------------------------------------------------------------------------------*/
    @AuraEnabled
    public static List<Collaborate_Support_Team__mdt> getOptions(string supportTeam) {
        List<Collaborate_Support_Team__mdt> CSTListValue=new List<Collaborate_Support_Team__mdt>();
        List<Collaborate_Support_Team__mdt> CSTList = new List<Collaborate_Support_Team__mdt>();
        CSTList=[SELECT Id,Label,developerName,buttonId__c,Queue__c,Reason__c,Support_Team__c,Type__c FROM Collaborate_Support_Team__mdt where Support_Team__c=:supportTeam ORDER By DeveloperName ASC limit 200];
        if(!CSTList.isEmpty()) {
            for(Collaborate_Support_Team__mdt objBT: CSTList) {
                CSTListValue.add(objBT);
            }
        }
        if(!CSTListValue.isEmpty()) {
            return CSTListValue; 
        }
        return null;
    }
    
    /* ----------------------------------------------------------------------------------------------------------------------
Name:         getCurrentUser
Description:  this function to query the current User Information
-------------------------------------------------------------------------------------------------------------------------*/
    @AuraEnabled
    
    public static User getCurrentUser() {
        User userInfo = [SELECT Id, FirstName, LastName,Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        return userInfo;
    }
}